version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    labels: [dependencies]
    groups:
      rust-compatible:
        patterns: ["*"]
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    labels: [dependencies, "area: ci"]
    groups:
      actions-compatible:
        patterns: ["*"]
        update-types: [minor, patch]
  - package-ecosystem: pip
    directory: /tracking
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    labels: [dependencies, "area: tracking"]
    groups:
      camera-compatible:
        patterns: ["*"]
        update-types: [minor, patch]
